[package]
name = "grrs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.23"
anyhow = "1.0"
# indicatif = "0.16.2"
log = "0.4.0"
env_logger = "0.9.0"
ctrlc = "3.2.2"

[dev-dependencies]
assert_cmd = "2.0"
assert_fs = "1.0"
predicates = "2.1"